Proxy_path = /afs/cern.ch/user/j/jodedra/private/x509up_u147761
Number = 1
arguments = $(Proxy_path) $(Number) $(ClusterId) $(ProcId)
executable              = genfilter.sh
output                  = welcome.$(ClusterId).$(ProcId).$(Number).out
error                   = welcome.$(ClusterId).$(ProcId).err
log                     = welcome.$(ClusterId).log
+MaxRuntime = 108000
initialdir = /afs/cern.ch/user/j/jodedra/gentry/CMSSW_11_2_4_patch1/src/
queue
