Proxy_path = /afs/cern.ch/user/j/jodedra/private/x509up_u147761
Number = 1
arguments = $(Proxy_path) $(Number) $(ClusterId) $(ProcId)
executable =  charmoniummctest.sh
output                  = welcome.$(ClusterId).$(ProcId).$(Number).out
error                   = welcome.$(ClusterId).$(ProcId).err
log                     = welcome.$(ClusterId).log
+MaxRuntime = 83000
initialdir = /afs/cern.ch/user/j/jodedra/charmoniumMC/CMSSW_11_2_4_patch1/src/Run3TriggerPerf-1/samples/mc/
queue